import Head from 'next/head'

import Navbar from '../components/Navbar'


import Footer from '../components/Footer'
import Main from '../components/Main'

export default function Home() {
  return (
    <>
      <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <header className="bg-black min-h-fit container">
        <Navbar />
      </header>
      <Main />
      <Footer />
    </>
  )
}
